@extends('layouts.app')
@section('title','Admin Secure Login | BloodNexus')
@section('content')
<style>
.admin-login-page{min-height:calc(100vh - 72px);display:grid;place-items:center;padding:45px 18px;background:radial-gradient(circle at 12% 15%,rgba(220,38,56,.12),transparent 26%),radial-gradient(circle at 88% 85%,rgba(99,102,241,.08),transparent 24%),linear-gradient(135deg,#f9fbff,#f4f6fb);position:relative;overflow:hidden}.admin-login-page:before{content:"";position:absolute;width:500px;height:500px;border-radius:50%;border:1px solid rgba(220,38,56,.10);right:-240px;top:-210px;box-shadow:0 0 0 35px rgba(220,38,56,.025),0 0 0 75px rgba(220,38,56,.018)}.admin-login-card{width:min(100%,470px);background:rgba(255,255,255,.90);backdrop-filter:blur(22px);border:1px solid #e6ebf2;border-radius:30px;padding:34px;box-shadow:0 30px 90px rgba(24,32,51,.12);position:relative;z-index:2;animation:loginIn .65s cubic-bezier(.2,.8,.2,1)}.admin-login-logo{width:74px;height:74px;border-radius:24px;padding:11px;background:#fff0f2;border:1px solid #ffdce1;box-shadow:0 16px 35px rgba(220,38,56,.13);margin:0 auto 18px;animation:logoFloat 2.8s ease-in-out infinite}.admin-login-logo img{width:100%;height:100%;object-fit:contain}.admin-login-kicker{text-align:center;font-size:9px;font-weight:900;letter-spacing:1.5px;color:#c51f36}.admin-login-title{text-align:center;font-size:30px;font-weight:950;letter-spacing:-1.2px;color:#182033;margin:7px 0}.admin-login-sub{text-align:center;color:#7c889b;font-size:12px;line-height:1.6;margin-bottom:25px}.admin-field{margin-bottom:15px}.admin-field label{font-size:10px;text-transform:uppercase;letter-spacing:.7px;font-weight:900;color:#4f5d72;margin-bottom:7px}.admin-field .form-control{height:49px;border-radius:14px;border:1px solid #e0e6ee;padding:0 14px;font-size:12px;box-shadow:none;transition:.22s}.admin-field .form-control:focus{border-color:#ef8a97;box-shadow:0 0 0 4px rgba(220,38,56,.08)}.admin-enter{height:51px;border:0;border-radius:15px;width:100%;background:linear-gradient(135deg,#dc2638,#a9142a);color:#fff;font-size:12px;font-weight:900;box-shadow:0 14px 30px rgba(220,38,56,.23);transition:.25s;position:relative;overflow:hidden}.admin-enter:hover{transform:translateY(-2px);box-shadow:0 18px 36px rgba(220,38,56,.28)}.admin-trust{display:flex;align-items:center;justify-content:center;gap:7px;margin-top:17px;color:#8793a5;font-size:9px;font-weight:700}.admin-trust i{color:#16a34a}.admin-back{text-align:center;margin-top:19px}.admin-back a{color:#64748b;font-size:10px;font-weight:800}.admin-back a:hover{color:#dc2638}@keyframes loginIn{from{opacity:0;transform:translateY(20px) scale(.98)}to{opacity:1;transform:none}}@keyframes logoFloat{50%{transform:translateY(-4px)}}
</style>
<div class="admin-login-page"><div class="admin-login-card">
<div class="admin-login-logo"><img src="{{ asset('images/bloodnexus-logo.svg') }}" alt="BloodNexus"></div>
<div class="admin-login-kicker">BLOODNEXUS COMMAND ACCESS</div><h1 class="admin-login-title">Welcome, Administrator</h1><p class="admin-login-sub">Securely enter the BloodNexus command center to manage blood operations, donors, intelligence and security.</p>
<form method="POST" action="{{ route('login.submit') }}">@csrf
<div class="admin-field"><label>Admin Email</label><input class="form-control" name="email" type="email" required autocomplete="username" placeholder="admin@bloodnexus.local"></div>
<div class="admin-field"><label>Password</label><input class="form-control" name="password" type="password" required autocomplete="current-password" placeholder="Enter your password"></div>
<button class="admin-enter bn-ripple" type="submit"><i class="bi bi-shield-lock-fill me-2"></i> Enter Command Center</button>
</form><div class="admin-trust"><i class="bi bi-check-circle-fill"></i> Protected admin session · Activity monitored</div><div class="admin-back"><a href="{{ route('login') }}"><i class="bi bi-arrow-left"></i> Back to main login</a></div>
</div></div>
@endsection
