@extends('layouts.app')
@section('title','Donor Home | BloodNexus')
@section('content')
<style>
.dh{background:radial-gradient(circle at 10% 10%,rgba(220,38,56,.12),transparent 30%),radial-gradient(circle at 90% 30%,rgba(124,58,237,.09),transparent 30%),#f7f9fc;padding:65px 0 90px}.dh-hero{position:relative;overflow:hidden;border-radius:32px;padding:50px;background:linear-gradient(135deg,#111827,#3b1020 55%,#7f1d1d);color:#fff;box-shadow:0 24px 70px rgba(127,29,29,.22)}.dh-hero:after{content:'🩸';position:absolute;right:35px;top:-35px;font-size:190px;opacity:.07;transform:rotate(-12deg)}.dh-kicker{display:inline-flex;padding:8px 13px;border-radius:30px;background:rgba(255,255,255,.11);border:1px solid rgba(255,255,255,.12);font-size:11px;font-weight:900;letter-spacing:1px;text-transform:uppercase}.dh-title{font-size:clamp(35px,5vw,62px);font-weight:900;letter-spacing:-2.5px;margin:20px 0 12px}.dh-sub{max-width:690px;color:#d9dce5;line-height:1.7}.dh-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.dh-btn{padding:13px 18px;border-radius:13px;font-weight:900;border:0}.dh-primary{background:#fff;color:#991b1b}.dh-secondary{background:rgba(255,255,255,.10);border:1px solid rgba(255,255,255,.18);color:#fff}.dh-card{height:100%;background:#fff;border:1px solid #e9edf3;border-radius:22px;padding:24px;box-shadow:0 12px 35px rgba(15,23,42,.06);transition:.25s}.dh-card:hover{transform:translateY(-5px);box-shadow:0 20px 45px rgba(15,23,42,.1)}.dh-icon{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:#fff0f2;color:#dc2638;font-size:22px;margin-bottom:14px}.dh-value{font-size:27px;font-weight:900;color:#111827}.dh-label{font-size:11px;color:#64748b;font-weight:800;text-transform:uppercase;letter-spacing:.7px}.dh-ai{background:linear-gradient(135deg,#fff,#f6f0ff);border-color:#e9ddff}.dh-ai .dh-icon{background:#ede9fe;color:#7c3aed}.dh-feature{display:flex;gap:13px;padding:15px 0;border-bottom:1px solid #eef2f7}.dh-feature:last-child{border-bottom:0}.dh-dot{width:38px;height:38px;border-radius:12px;background:#fff1f3;color:#dc2638;display:grid;place-items:center;flex:0 0 auto}
</style>
<div class="dh"><div class="container">
    <div class="dh-hero mb-4">
        <span class="dh-kicker">❤️ Verified Donor Center</span>
        <h1 class="dh-title">Your blood can become someone's second chance.</h1>
        <p class="dh-sub">Welcome back, <strong>{{ auth()->user()->name }}</strong>. BloodNexus prioritizes matching blood-group requests, critical emergencies and your local area while keeping other matching cities visible.</p>
        <div class="dh-actions"><a href="{{ route('donor.dashboard') }}" class="dh-btn dh-primary">Open Donor Dashboard</a><a href="{{ route('donor.requests') }}" class="dh-btn dh-secondary">Donation History</a><a href="{{ route('ai.assistant') }}" class="dh-btn dh-secondary">🤖 Ask BloodNexus AI</a></div>
    </div>
    <div class="row g-4 mb-4">
        <div class="col-md-4"><div class="dh-card"><div class="dh-icon">🩸</div><div class="dh-label">Your Blood Group</div><div class="dh-value">{{ auth()->user()->donor?->blood_group ?? auth()->user()->blood_group ?? '—' }}</div></div></div>
        <div class="col-md-4"><div class="dh-card"><div class="dh-icon">📍</div><div class="dh-label">Registered City</div><div class="dh-value" style="font-size:21px">{{ auth()->user()->donor?->city ?? auth()->user()->city ?? '—' }}</div></div></div>
        <div class="col-md-4"><div class="dh-card dh-ai"><div class="dh-icon">✨</div><div class="dh-label">AI Support</div><div class="dh-value" style="font-size:21px">Live Matching</div><div class="small text-muted mt-1">Ask about requests, eligibility and donor insights.</div></div></div>
    </div>
    <div class="row g-4">
        <div class="col-lg-7"><div class="dh-card"><h4 class="fw-black mb-1">Donor Mission Control</h4><p class="text-secondary small mb-3">Everything you need before responding to a blood request.</p><div class="dh-feature"><div class="dh-dot">🚨</div><div><strong>Critical requests first</strong><div class="small text-secondary">Emergency requests are ranked above urgent and normal requests.</div></div></div><div class="dh-feature"><div class="dh-dot">🧬</div><div><strong>Blood group matching</strong><div class="small text-secondary">Only requests matching your registered blood group are presented.</div></div></div><div class="dh-feature"><div class="dh-dot">📍</div><div><strong>City priority, not city lock</strong><div class="small text-secondary">Your city appears first, but other cities with your blood group remain visible.</div></div></div></div></div>
        <div class="col-lg-5"><div class="dh-card dh-ai"><div class="dh-icon">🤖</div><h4 class="fw-black">BloodNexus AI</h4><p class="text-secondary">Your donor-side AI can inspect live matching requests, emergency demand, availability and your donation cooldown.</p><a href="{{ route('ai.assistant') }}" class="btn btn-dark rounded-pill px-4">Open AI Assistant</a></div></div>
    </div>
</div></div>
@endsection
