@extends('layouts.app')
@section('title', 'Forgot Password | BloodNexus')
@section('content')
<style>
.bn-reset-page{min-height:calc(100vh - 78px);padding:55px 0 75px;background:radial-gradient(circle at 10% 15%,rgba(220,38,56,.10),transparent 28%),radial-gradient(circle at 90% 80%,rgba(99,102,241,.08),transparent 30%),linear-gradient(135deg,#fbfcff,#f7f8fc 55%,#fff7f8)}.bn-reset-card{max-width:760px;margin:auto;background:#fff;border:1px solid #edf0f5;border-radius:30px;padding:38px;box-shadow:0 24px 65px rgba(17,24,39,.11)}.bn-reset-icon{width:76px;height:76px;border-radius:25px;background:#fff0f2;color:#c51e35;display:flex;align-items:center;justify-content:center;font-size:32px;box-shadow:0 12px 28px rgba(220,38,56,.12);animation:bnFloat 3s ease-in-out infinite}.bn-reset-input{min-height:54px;border-radius:16px!important;border-color:#dfe4ec!important;box-shadow:none!important}.bn-reset-input:focus{border-color:#dc2638!important;box-shadow:0 0 0 4px rgba(220,38,56,.08)!important}.bn-reset-btn{min-height:55px;border-radius:16px;font-weight:900;box-shadow:0 13px 28px rgba(220,38,56,.20)}.bn-reset-note{background:#f8fafc;border:1px solid #e7edf5;border-radius:18px;padding:15px;color:#64748b}@keyframes bnFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}
</style>
<div class="bn-reset-page"><div class="container"><div class="bn-reset-card bn-reveal"><div class="text-center"><div class="bn-reset-icon mx-auto mb-4"><i class="bi bi-key-fill"></i></div><span class="bn-portal-chip"><i class="bi bi-shield-lock-fill"></i> SECURE PASSWORD RECOVERY</span><h2 class="mt-3" style="font-weight:900;letter-spacing:-1.2px">Forgot your password?</h2><p class="text-secondary mx-auto" style="max-width:560px">Enter the real, verified email connected to your BloodNexus account. We'll send a secure password-reset link to that inbox.</p></div>
@if(session('status'))<div class="alert alert-success rounded-4 border-0 mt-4">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger rounded-4 border-0 mt-4"><ul class="mb-0 ps-3">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('password.email') }}" class="mt-4">@csrf<label class="form-label fw-bold">Registered Email Address</label><div class="position-relative"><i class="bi bi-envelope position-absolute top-50 start-0 translate-middle-y ms-3 text-secondary"></i><input type="email" name="email" value="{{ old('email') }}" class="form-control bn-reset-input ps-5" placeholder="you@gmail.com" required autofocus></div><div class="small text-secondary mt-2"><i class="bi bi-info-circle me-1"></i>Only verified BloodNexus user/donor accounts can reset a password.</div><button class="btn btn-danger w-100 bn-reset-btn mt-4"><i class="bi bi-send-fill me-2"></i>Send Real Reset Link</button></form>
<div class="bn-reset-note mt-4"><i class="bi bi-envelope-check text-danger me-1"></i><strong>Check your inbox.</strong> The reset link is sent through the configured SMTP email account. If you don't receive it, check Spam/Junk and your mail configuration.</div><div class="text-center mt-4 pt-3 border-top"><a href="{{ route('login') }}" class="small fw-bold text-danger text-decoration-none">← Back to Login</a></div>
</div></div></div>
@endsection
