@extends('layouts.app')
@section('title', 'Login | BloodNexus')
@section('content')
<div class="bn-auth-page position-relative overflow-hidden"><span class="bn-floating-drop" style="top:14%;left:8%"></span><span class="bn-floating-drop" style="top:28%;right:9%;animation-delay:1.4s"></span><span class="bn-floating-drop" style="bottom:18%;left:15%;animation-delay:2.2s"></span>
<div class="container py-5 position-relative" style="z-index:2"><div class="row justify-content-center align-items-center g-5">
<div class="col-xl-4 col-lg-5 d-none d-lg-block bn-reveal"><div class="bn-auth-side"><span class="bn-portal-chip mb-3"><i class="bi bi-shield-check"></i> SECURE BLOOD CONNECT</span><h1>Welcome back to <span>BloodNexus.</span></h1><p>Sign in to continue finding blood, responding to requests and staying connected with your life-saving network.</p><div class="bn-side-list"><div><i class="bi bi-check2-circle"></i><span>Smart blood-group matching</span></div><div><i class="bi bi-check2-circle"></i><span>Live request tracking</span></div><div><i class="bi bi-check2-circle"></i><span>Secure role-based access</span></div></div><div class="bn-side-orbit"><span class="bn-side-drop">🩸</span></div></div></div>
<div class="col-xl-5 col-lg-6"><div class="premium-card bg-white p-4 p-md-5 bn-form-shell bn-reveal"><div class="bn-form-content">
<div class="bn-form-icon mb-4"><svg viewBox="0 0 48 48" fill="none"><path d="M24 4S9 22 9 31a15 15 0 0 0 30 0C39 22 24 4 24 4Z" fill="url(#loginGrad)"/><path d="M24 16v16M16 24h16" stroke="#fff" stroke-width="4" stroke-linecap="round"/><defs><linearGradient id="loginGrad" x1="8" y1="4" x2="40" y2="40"><stop stop-color="#ff5267"/><stop offset="1" stop-color="#b9152d"/></linearGradient></defs></svg></div>
<span class="bn-portal-chip mb-3"><i class="bi bi-lock-fill"></i> SECURE LOGIN</span><h2 class="fw-black mb-2" style="font-weight:900;letter-spacing:-1px">Welcome back</h2><p class="text-secondary mb-4">Login to your BloodNexus account and continue your journey.</p>
<form method="POST" action="{{ route('login.submit') }}" class="bn-stagger">@csrf @if(session('login_warning'))<input type="hidden" name="security_warning_ack" value="1">@endif
<div><label class="form-label fw-bold">Email Address</label><div class="position-relative"><i class="bi bi-envelope position-absolute top-50 start-0 translate-middle-y ms-3 text-secondary"></i><input type="email" name="email" value="{{ old('email') }}" class="form-control ps-5 bn-input @error('email') is-invalid @enderror" placeholder="you@example.com" required></div>@error('email')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
<div><label class="form-label fw-bold mt-3">Password</label><div class="position-relative"><i class="bi bi-shield-lock position-absolute top-50 start-0 translate-middle-y ms-3 text-secondary"></i><input id="bnLoginPassword" type="password" name="password" class="form-control ps-5 pe-5 bn-input @error('password') is-invalid @enderror" placeholder="Enter your password" required><button type="button" class="btn position-absolute top-50 end-0 translate-middle-y border-0 text-secondary" onclick="bnTogglePassword('bnLoginPassword',this)"><i class="bi bi-eye"></i></button></div>@error('password')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
@if(session('login_warning'))<div class="alert bn-security-alert rounded-4 mt-3"><div class="fw-bold"><i class="bi bi-exclamation-triangle-fill me-1"></i> Security warning</div><div class="small mt-1">You have logged in <strong>{{ session('login_count_today') }}</strong> time(s) today. Frequent login activity is monitored.</div><div class="small mt-2 fw-semibold">Warning: {{ session('login_warning_threshold') }} · Block: {{ session('login_block_threshold') }}</div></div>@endif
@if(session('account_blocked'))<div class="alert alert-danger border-0 rounded-4 mt-3"><div class="fw-bold"><i class="bi bi-shield-x me-1"></i> Account blocked</div><div class="small mt-1">Your account cannot log in until an administrator reviews the security event.</div><a href="{{ route('account.review', ['email' => old('email')]) }}" class="btn btn-sm btn-dark rounded-pill mt-3">Submit / Track Appeal</a></div>@endif
<div class="d-flex justify-content-between align-items-center mt-3 mb-4"><label class="form-check d-flex align-items-center gap-2 mb-0"><input class="form-check-input" type="checkbox" name="remember" id="remember"><span class="small fw-semibold">Remember me</span></label><a href="{{ route('password.request') }}" class="small fw-bold text-danger">Forgot password?</a></div>
<button class="btn btn-danger w-100 bn-submit bn-ripple"><i class="bi bi-box-arrow-in-right me-2"></i>Login to BloodNexus</button></form>
@if(session('account_locked'))<div class="alert alert-warning rounded-4 mt-3"><strong>Account temporarily locked.</strong><br><a href="{{ route('account.review', ['email'=>old('email')]) }}" class="fw-bold">Request Account Review</a></div>@endif @if(session('status'))<div class="alert alert-success rounded-4 mt-3">{{ session('status') }}</div>@endif
<div class="text-center mt-4 pt-3 border-top"><p class="text-secondary small mb-2">Don't have a BloodNexus account?</p><div class="d-flex justify-content-center gap-2 flex-wrap"><a href="{{ route('register.user') }}" class="btn btn-light border rounded-pill px-3 fw-bold"><i class="bi bi-droplet-half me-1"></i>I Need Blood</a><a href="{{ route('register.donor') }}" class="btn btn-light border rounded-pill px-3 fw-bold"><i class="bi bi-heart-pulse me-1"></i>I Want to Donate</a></div></div>
</div></div></div></div></div>
<style>.bn-auth-page{min-height:calc(100vh - 78px);background:radial-gradient(circle at 10% 15%,rgba(220,38,56,.10),transparent 28%),radial-gradient(circle at 90% 80%,rgba(124,58,237,.08),transparent 28%),linear-gradient(135deg,#fbfcff,#f7f8fc 55%,#fff6f7)}.bn-form-shell{animation:bnLoginCardIn .8s cubic-bezier(.18,.8,.2,1) both}.bn-form-shell:hover{transform:translateY(-3px);box-shadow:0 28px 70px rgba(15,23,42,.13)!important}.bn-auth-side{position:relative;min-height:520px;padding:30px 10px 20px}.bn-auth-side h1{font-size:clamp(42px,4.5vw,64px);line-height:1.02;font-weight:900;letter-spacing:-3px;color:#111827;margin:18px 0}.bn-auth-side h1 span{color:#dc2638;display:block}.bn-auth-side p{font-size:16px;line-height:1.7;color:#64748b;max-width:470px}.bn-side-list{display:grid;gap:12px;margin-top:25px}.bn-side-list div{display:flex;align-items:center;gap:10px;font-size:13px;font-weight:800;color:#334155}.bn-side-list i{color:#dc2638;font-size:18px}.bn-side-orbit{position:absolute;width:260px;height:260px;border:1px solid rgba(220,38,56,.12);border-radius:50%;right:-20px;bottom:-10px;animation:bnOrbit 15s linear infinite}.bn-side-orbit:before{content:"";position:absolute;inset:28px;border:1px dashed rgba(124,58,237,.13);border-radius:50%}.bn-side-drop{position:absolute;right:15px;top:38px;font-size:45px;filter:drop-shadow(0 12px 22px rgba(220,38,56,.2));animation:bnIconFloat 3s ease-in-out infinite}@keyframes bnOrbit{to{transform:rotate(360deg)}} @keyframes bnLoginCardIn{from{opacity:0;transform:translateY(28px) scale(.98)}to{opacity:1;transform:translateY(0) scale(1)}} </style><script>function bnTogglePassword(id,btn){const input=document.getElementById(id),icon=btn.querySelector('i');if(input.type==='password'){input.type='text';icon.className='bi bi-eye-slash'}else{input.type='password';icon.className='bi bi-eye'}}</script>
@endsection
