@extends('layouts.app')
@section('title', 'Create New Password | BloodNexus')
@section('content')
<style>
.bn-reset-page{min-height:calc(100vh - 78px);padding:55px 0 75px;background:radial-gradient(circle at 10% 15%,rgba(220,38,56,.10),transparent 28%),radial-gradient(circle at 90% 80%,rgba(99,102,241,.08),transparent 30%),linear-gradient(135deg,#fbfcff,#f7f8fc 55%,#fff7f8)}.bn-reset-card{max-width:650px;margin:auto;background:#fff;border:1px solid #edf0f5;border-radius:30px;padding:38px;box-shadow:0 24px 65px rgba(17,24,39,.11)}.bn-reset-icon{width:76px;height:76px;border-radius:25px;background:#fff0f2;color:#c51e35;display:flex;align-items:center;justify-content:center;font-size:32px;box-shadow:0 12px 28px rgba(220,38,56,.12)}.bn-reset-input{min-height:54px;border-radius:16px!important;border-color:#dfe4ec!important;box-shadow:none!important}.bn-reset-input:focus{border-color:#dc2638!important;box-shadow:0 0 0 4px rgba(220,38,56,.08)!important}.bn-reset-btn{min-height:55px;border-radius:16px;font-weight:900;box-shadow:0 13px 28px rgba(220,38,56,.20)}
</style>
<div class="bn-reset-page"><div class="container"><div class="bn-reset-card bn-reveal"><div class="text-center"><div class="bn-reset-icon mx-auto mb-4"><i class="bi bi-shield-lock-fill"></i></div><span class="bn-portal-chip"><i class="bi bi-key-fill"></i> SECURE PASSWORD RESET</span><h2 class="mt-3" style="font-weight:900;letter-spacing:-1.2px">Create a new password</h2><p class="text-secondary">Your reset link is valid for a limited time. Choose a strong new password.</p></div>
@if($errors->any())<div class="alert alert-danger rounded-4 border-0 mt-4"><ul class="mb-0 ps-3">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('password.update') }}" class="mt-4">@csrf<input type="hidden" name="token" value="{{ $token }}"><div class="mb-3"><label class="form-label fw-bold">Verified Email</label><input type="email" name="email" value="{{ old('email',$email) }}" class="form-control bn-reset-input" required></div><div class="mb-3"><label class="form-label fw-bold">New Password</label><input type="password" name="password" class="form-control bn-reset-input" minlength="8" required></div><div class="mb-4"><label class="form-label fw-bold">Confirm Password</label><input type="password" name="password_confirmation" class="form-control bn-reset-input" minlength="8" required></div><button class="btn btn-danger w-100 bn-reset-btn"><i class="bi bi-check2-circle me-2"></i>Update Password</button></form><div class="text-center mt-4 pt-3 border-top"><a href="{{ route('login') }}" class="small fw-bold text-danger text-decoration-none">← Back to Login</a></div>
</div></div></div>
@endsection
