@extends('layouts.admin')
@section('title','Blood Requests')
@section('content')
<div class="admin-pagebar"><div><h1 class="page-title">Blood Requests</h1><div class="admin-page-subtitle">Review, assign donors and update every request.</div></div></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="admin-card"><div class="admin-card-body"><div class="small text-secondary">Total Requests</div><div class="fs-3 fw-bold">{{ $requests->total() }}</div></div></div></div><div class="col-md-4"><div class="admin-card"><div class="admin-card-body"><div class="small text-secondary">Cancelled Requests</div><div class="fs-3 fw-bold text-danger">{{ \App\Models\BloodRequest::where('status','cancelled')->count() }}</div><div class="small text-secondary">Live count — filter Status = Cancelled below.</div></div></div></div><div class="col-md-4"><div class="admin-card"><div class="admin-card-body"><div class="small text-secondary">Current View</div><div class="fs-5 fw-bold">{{ request('status') ? ucfirst(request('status')) : 'All requests' }}</div></div></div></div></div>
<div class="admin-card mb-4"><div class="admin-card-body"><form class="row g-2" method="GET"><div class="col-md-3"><input class="form-control filter-control" name="search" value="{{ request('search') }}" placeholder="Patient / city / hospital"></div><div class="col-md-2"><select class="form-select filter-control" name="status"><option value="">All status</option>@foreach(['pending','matched','accepted','rejected','completed','cancelled'] as $x)<option value="{{ $x }}" @selected(request('status')===$x)>{{ ucfirst($x) }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select filter-control" name="urgency"><option value="">All urgency</option>@foreach(['normal','urgent','critical'] as $x)<option value="{{ $x }}" @selected(request('urgency')===$x)>{{ ucfirst($x) }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select filter-control" name="blood_group"><option value="">All blood groups</option>@foreach(['A+','A-','B+','B-','AB+','AB-','O+','O-'] as $x)<option value="{{ $x }}" @selected(request('blood_group')===$x)>{{ $x }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn-admin btn-dark w-100 py-2" type="submit">Filter</button></div><div class="col-md-1"><a class="btn-admin btn-light-admin w-100 d-block text-center py-2" href="{{ route('admin.requests') }}">Reset</a></div></form></div></div>
<div class="admin-card"><div class="table-wrap"><table class="table admin-table mb-0"><thead><tr><th>ID</th><th>Patient</th><th>Blood</th><th>Location</th><th>Urgency</th><th>Donor</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($requests as $r)<tr><td>#{{ $r->id }}</td><td><strong>{{ $r->patient_name }}</strong><div class="text-muted">{{ $r->user?->name ?? 'User removed' }}</div></td><td><span class="badge bg-danger-subtle text-danger">{{ $r->blood_group }}</span></td><td>{{ $r->city }}<div class="text-muted">{{ $r->hospital }}</div>@if($r->status==='cancelled')<div class="text-danger small mt-1"><i class="bi bi-x-circle me-1"></i>Cancelled {{ $r->updated_at?->format('d M Y h:i A') }}</div>@endif</td><td>{{ ucfirst($r->urgency) }}</td><td>{{ $r->donor?->name ?? 'Not assigned' }}</td><td><span class="badge-soft status-{{ $r->status }}">{{ strtoupper($r->status) }}</span></td><td><div class="d-flex gap-1"><button class="btn-admin btn-light-admin" data-bs-toggle="modal" data-bs-target="#assign{{ $r->id }}">Assign</button><form method="POST" action="{{ route('admin.request.status',$r) }}">@csrf<input type="hidden" name="status" value="completed"><button class="btn-admin btn-red" type="submit" @disabled($r->status==='completed'||!$r->donor_id)>Complete</button></form><form method="POST" action="{{ route('admin.request.delete',$r) }}" onsubmit="return confirm('Delete this request?')">@csrf @method('DELETE')<button class="btn-admin btn-light-admin text-danger" type="submit">Delete</button></form></div></td></tr>
<div class="modal fade" id="assign{{ $r->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.request.assign',$r) }}">@csrf<div class="modal-header"><h5 class="modal-title">Assign Donor #{{ $r->id }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select name="donor_id" class="form-select" required><option value="">Choose matching donor</option>@foreach($donors as $d) @if(strcasecmp(trim($d->blood_group),trim($r->blood_group))===0)<option value="{{ $d->id }}">{{ $d->name }} · {{ $d->blood_group }} · {{ $d->city }}</option>@endif @endforeach</select></div><div class="modal-footer"><button class="btn-admin btn-red">Assign Donor</button></div></form></div></div></div>
@empty<tr><td colspan="8"><div class="empty-state">No requests found.</div></td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $requests->onEachSide(1)->links('pagination::bootstrap-5') }}</div></div>
@endsection
