<?php $__env->startSection('title','Admin Dashboard'); ?>
<?php $__env->startPush('styles'); ?>
<style>
.command-hero{position:relative;overflow:hidden;border-radius:30px;padding:30px;background:linear-gradient(135deg,#fff 0%,#fff7f8 48%,#f4f7ff 100%);border:1px solid #e7ebf2;box-shadow:0 25px 65px rgba(24,32,51,.08)}
.command-hero:before{content:"";position:absolute;width:420px;height:420px;border-radius:50%;right:-180px;top:-230px;border:1px solid rgba(220,38,56,.13);box-shadow:0 0 0 30px rgba(220,38,56,.025),0 0 0 70px rgba(220,38,56,.018)}
.command-hero:after{content:"";position:absolute;width:10px;height:10px;border-radius:50%;right:18%;top:28%;background:#dc2638;box-shadow:0 0 0 8px rgba(220,38,56,.10),0 0 28px rgba(220,38,56,.35);animation:floatDot 2.5s ease-in-out infinite}
.hero-kicker{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border-radius:999px;background:#fff;border:1px solid #ffd8de;color:#c51f36;font-size:10px;font-weight:900;letter-spacing:1.1px;box-shadow:0 8px 22px rgba(220,38,56,.07)}
.hero-title{font-size:36px;line-height:1.08;font-weight:950;letter-spacing:-1.7px;margin:14px 0 8px;max-width:700px}.hero-title span{color:#dc2638}.hero-sub{color:#718096;font-size:13px;max-width:650px;line-height:1.65}.hero-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}.hero-chip{display:inline-flex;align-items:center;gap:7px;padding:9px 11px;border-radius:12px;background:rgba(255,255,255,.82);border:1px solid #e9edf3;font-size:10px;font-weight:800;color:#516076}.hero-chip i{color:#dc2638}.hero-orb{position:absolute;right:70px;bottom:25px;width:150px;height:150px;border-radius:50%;border:1px dashed rgba(220,38,56,.18);display:grid;place-items:center}.hero-orb-inner{width:92px;height:92px;border-radius:28px;background:linear-gradient(135deg,#dc2638,#a9142a);display:grid;place-items:center;color:white;font-size:42px;box-shadow:0 22px 42px rgba(220,38,56,.28);animation:orbFloat 3s ease-in-out infinite}
.metric-card{background:rgba(255,255,255,.92);border:1px solid #e7ebf2;border-radius:22px;padding:19px;position:relative;overflow:hidden;box-shadow:0 14px 34px rgba(24,32,51,.055);transition:.3s ease}.metric-card:hover{transform:translateY(-6px);box-shadow:0 24px 45px rgba(220,38,56,.10);border-color:#ffd5db}.metric-top{display:flex;align-items:center;justify-content:space-between}.metric-icon{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:#fff0f2;color:#dc2638;box-shadow:inset 0 0 0 1px #ffe0e5}.metric-label{margin-top:14px;font-size:10px;text-transform:uppercase;letter-spacing:.9px;font-weight:900;color:#8190a6}.metric-value{font-size:29px;font-weight:950;letter-spacing:-1px;margin-top:3px;color:#182033}.metric-foot{font-size:10px;color:#9aa6b7;margin-top:4px}.metric-glow{position:absolute;width:100px;height:100px;border-radius:50%;right:-48px;top:-48px;background:rgba(220,38,56,.045)}
.section-shell{border-radius:24px;background:rgba(255,255,255,.88);border:1px solid #e7ebf2;box-shadow:0 16px 40px rgba(24,32,51,.055);overflow:hidden}.section-head{padding:17px 19px;border-bottom:1px solid #edf0f5;display:flex;align-items:center;justify-content:space-between;gap:12px}.section-title{font-weight:950;font-size:14px;color:#202b3f}.section-sub{font-size:10px;color:#8a98aa;margin-top:3px}.section-body{padding:18px}.security-item,.critical-item,.donation-item{display:flex;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid #f0f2f6}.security-item:last-child,.critical-item:last-child,.donation-item:last-child{border-bottom:0}.icon-box{width:40px;height:40px;border-radius:13px;display:grid;place-items:center;flex:none}.security-item .icon-box{background:#fff0f2;color:#dc2638}.critical-item .icon-box{background:#fff5f5;color:#dc2638;font-weight:950}.donation-item .icon-box{background:#fff0f2;color:#dc2638}.item-main{min-width:0;flex:1}.item-main strong{display:block;font-size:11px;color:#293449}.item-main small{display:block;color:#95a1b1;font-size:9px;margin-top:3px}.risk-row{padding:10px 0;border-bottom:1px solid #f0f2f6}.risk-row:last-child{border-bottom:0}.risk-meta{display:flex;justify-content:space-between;font-size:10px;font-weight:800}.risk-bar{height:8px;background:#edf1f5;border-radius:99px;overflow:hidden;margin-top:7px}.risk-fill{height:100%;border-radius:99px;background:linear-gradient(90deg,#ff8a98,#dc2638);animation:barIn .9s ease both}.quick-action{display:flex;align-items:center;justify-content:space-between;padding:14px 15px;border:1px solid #e9edf3;background:#fff;border-radius:15px;color:#334155;font-size:11px;font-weight:850;transition:.25s}.quick-action:hover{transform:translateX(5px);border-color:#ffd3da;color:#dc2638;box-shadow:0 10px 25px rgba(220,38,56,.07)}.quick-action i{font-size:17px;color:#dc2638}.intel-card{padding:18px;border-radius:20px;border:1px solid #edf0f4;background:linear-gradient(135deg,#fff,#fbfcfe);transition:.25s}.intel-card:hover{transform:translateY(-3px);box-shadow:0 15px 30px rgba(24,32,51,.06)}.intel-icon{width:38px;height:38px;border-radius:12px;background:#fff0f2;color:#dc2638;display:grid;place-items:center;margin-bottom:11px}.intel-card strong{font-size:12px}.intel-card p{font-size:10px;color:#8b97a8;margin:6px 0 0;line-height:1.55}
@keyframes floatDot{50%{transform:translateY(12px)}}@keyframes orbFloat{50%{transform:translateY(-7px) rotate(2deg)}}@keyframes barIn{from{width:0}}@media(max-width:900px){.hero-orb{display:none}.hero-title{font-size:29px}}
</style>
<?php $__env->stopPush(); ?>
<?php $__env->startSection('content'); ?>
<div class="command-hero mb-4">
    <div class="position-relative" style="z-index:2">
        <span class="hero-kicker"><i class="bi bi-stars"></i> BLOODNEXUS COMMAND CENTER</span>
        <h1 class="hero-title">Control the network.<br><span>Save time when it matters.</span></h1>
        <p class="hero-sub">Welcome back, <strong><?php echo e(session('fixed_admin_name') ?? auth()->user()->name ?? 'Administrator'); ?></strong>. Monitor donors, blood demand, critical requests and security signals from one premium workspace.</p>
        <div class="hero-actions">
            <a href="<?php echo e(route('admin.requests')); ?>" class="btn-admin btn-red bn-ripple"><i class="bi bi-droplet-fill"></i> Blood Intelligence</a>
            <a href="<?php echo e(route('admin.donor.intelligence')); ?>" class="btn-admin btn-light-admin bn-ripple"><i class="bi bi-heart-pulse-fill"></i> Donor Intelligence</a>
            <span class="hero-chip"><i class="bi bi-broadcast-pin"></i> Live monitoring</span><span class="hero-chip"><i class="bi bi-shield-check"></i> Security protected</span>
        </div>
    </div><div class="hero-orb"><div class="hero-orb-inner"><i class="bi bi-droplet-half"></i></div></div>
</div>
<div class="row g-3 mb-4">
<?php $__currentLoopData = [['Blood Seekers',$totalUsers,'bi-people-fill'],['Total Donors',$totalDonors,'bi-heart-pulse-fill'],['Active Requests',$activeRequests,'bi-droplet-half'],['Completed',$completedRequests,'bi-check2-circle']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<div class="col-6 col-xl-3"><div class="metric-card"><span class="metric-glow"></span><div class="metric-top"><div class="metric-icon"><i class="bi <?php echo e($s[2]); ?>"></i></div><span class="badge-soft">LIVE</span></div><div class="metric-label"><?php echo e($s[0]); ?></div><div class="metric-value"><?php echo e($s[1]); ?></div><div class="metric-foot">Synced with database</div></div></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div>
<div class="row g-4 mb-4">
<div class="col-xl-7"><div class="section-shell h-100"><div class="section-head"><div><div class="section-title"><i class="bi bi-shield-exclamation text-danger me-1"></i> Security Watch</div><div class="section-sub"><?php echo e($openSecurityAlerts); ?> unresolved high-risk event(s)</div></div><a href="<?php echo e(route('admin.security')); ?>" class="btn-admin btn-dark">Security Center <i class="bi bi-arrow-up-right"></i></a></div><div class="section-body">
<?php $__empty_1 = true; $__currentLoopData = $securityAlerts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="security-item"><div class="icon-box"><i class="bi bi-shield-exclamation"></i></div><div class="item-main"><strong><?php echo e($log->incident_id); ?> · <?php echo e($log->message); ?></strong><small><?php echo e($log->user?->name ?? 'System'); ?> · <?php echo e($log->ip_address ?? '-'); ?> · <?php echo e($log->created_at?->diffForHumans()); ?></small></div><span class="badge-soft <?php echo e($log->severity==='critical'?'status-rejected':'status-pending'); ?>"><?php echo e(strtoupper($log->severity)); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="empty-state py-4">No unresolved high-risk security alerts.</div><?php endif; ?>
</div></div></div>
<div class="col-xl-5"><div class="section-shell h-100"><div class="section-head"><div><div class="section-title"><i class="bi bi-lightning-charge-fill text-danger me-1"></i> Quick Actions</div><div class="section-sub">Jump directly into operations</div></div></div><div class="section-body d-grid gap-2">
<?php $__currentLoopData = [[route('admin.requests'),'bi-clipboard2-pulse','Manage Blood Requests'],[route('admin.donors'),'bi-heart-pulse','Manage Donors'],[route('admin.users'),'bi-people','Manage Blood Seekers'],[route('admin.donations'),'bi-clock-history','Donation History']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $a): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="quick-action" href="<?php echo e($a[0]); ?>"><span><i class="bi <?php echo e($a[1]); ?> me-2"></i><?php echo e($a[2]); ?></span><i class="bi bi-arrow-right"></i></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div></div></div>
</div>
<div class="row g-4 mb-4">
<div class="col-lg-6"><div class="section-shell h-100"><div class="section-head"><div><div class="section-title"><i class="bi bi-droplet-fill text-danger me-1"></i> Blood Group Overview</div><div class="section-sub">Current donor profile distribution</div></div><span class="badge-soft">8 GROUPS</span></div><div class="section-body"><?php ($max=max(array_values($bloodGroupStats ?: ['x'=>1]))); ?> <?php $__currentLoopData = ['A+','A-','B+','B-','AB+','AB-','O+','O-']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $g): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <?php ($c=(int)($bloodGroupStats[$g]??0)); ?><div class="risk-row"><div class="risk-meta"><span><?php echo e($g); ?></span><span><?php echo e($c); ?> donors</span></div><div class="risk-bar"><div class="risk-fill" style="width:<?php echo e($max?($c/$max*100):0); ?>%"></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div></div>
<div class="col-lg-6"><div class="section-shell h-100"><div class="section-head"><div><div class="section-title"><i class="bi bi-exclamation-triangle-fill text-danger me-1"></i> Blood Shortage Risk</div><div class="section-sub">Demand versus available donors</div></div><span class="badge-soft status-pending">AI SIGNAL</span></div><div class="section-body"><?php $__empty_1 = true; $__currentLoopData = $shortageRisk; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="risk-row"><div class="risk-meta"><span><?php echo e($r->blood_group); ?></span><span><?php echo e($r->risk); ?>/100</span></div><div class="risk-bar"><div class="risk-fill" style="width:<?php echo e(min(100,(int)$r->risk)); ?>%"></div></div><div class="text-muted mt-1" style="font-size:9px"><?php echo e($r->demand); ?> requests · <?php echo e($r->available); ?> available</div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="empty-state py-4">No demand data yet.</div><?php endif; ?></div></div></div>
</div>
<div class="row g-4 mb-4">
<div class="col-xl-7"><div class="section-shell h-100"><div class="section-head"><div><div class="section-title"><i class="bi bi-activity text-danger me-1"></i> Critical Blood Requests</div><div class="section-sub">Requests that need immediate attention</div></div><a class="btn-admin btn-light-admin" href="<?php echo e(route('admin.critical')); ?>">View all <i class="bi bi-arrow-right"></i></a></div><div class="section-body"><?php $__empty_1 = true; $__currentLoopData = $criticalRequests; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="critical-item"><div class="icon-box"><?php echo e($r->blood_group); ?></div><div class="item-main"><strong><?php echo e($r->patient_name); ?></strong><small><?php echo e($r->city); ?> · <?php echo e($r->hospital); ?></small></div><span class="badge-soft status-<?php echo e($r->status); ?>"><?php echo e(strtoupper($r->status)); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="empty-state py-4">No critical requests right now.</div><?php endif; ?></div></div></div>
<div class="col-xl-5"><div class="section-shell h-100"><div class="section-head"><div><div class="section-title"><i class="bi bi-droplet-fill text-danger me-1"></i> Recent Donations</div><div class="section-sub">Latest completed donation activity</div></div></div><div class="section-body"><?php $__empty_1 = true; $__currentLoopData = $recentDonations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="donation-item"><div class="icon-box"><i class="bi bi-heart-fill"></i></div><div class="item-main"><strong><?php echo e($d->donor?->name ?? 'Unknown donor'); ?> → <?php echo e($d->patient_name); ?></strong><small><?php echo e($d->blood_group); ?> · <?php echo e(optional($d->completed_at)->format('d M Y, h:i A') ?? 'Time unavailable'); ?></small></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="empty-state py-4">No completed donations yet.</div><?php endif; ?></div></div></div>
</div>
<div class="section-shell"><div class="section-head"><div><div class="section-title"><i class="bi bi-stars text-danger me-1"></i> BloodNexus Intelligence</div><div class="section-sub">Automated signals generated from existing project data</div></div><span class="badge-soft <?php echo e($suspiciousRequests>5?'status-rejected':'status-accepted'); ?>"><?php echo e($suspiciousRequests); ?> critical/emergency · 24h</span></div><div class="section-body"><div class="row g-3"><div class="col-md-4"><div class="intel-card"><div class="intel-icon"><i class="bi bi-graph-up-arrow"></i></div><strong>Demand Prediction</strong><p>Uses request history, location and urgency patterns to highlight rising demand.</p></div></div><div class="col-md-4"><div class="intel-card"><div class="intel-icon"><i class="bi bi-person-check-fill"></i></div><strong>Donor Match Engine</strong><p>Ranks compatible donors using blood group, location and availability signals.</p></div></div><div class="col-md-4"><div class="intel-card"><div class="intel-icon"><i class="bi bi-shield-lock-fill"></i></div><strong>Security Monitoring</strong><p>Tracks failed logins and suspicious activity so admins can respond quickly.</p></div></div></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\BloodNexus\resources\views/admin/dashboard.blade.php ENDPATH**/ ?>